//custom class
window.UNITY_BODY_UI_REGISTRY = {};

class UnityBodyUI extends HTMLElement {
    #myGameInstance = null;

    constructor() {
        super();
        this.innerHTML = this.template;

        window.UNITY_BODY_UI_REGISTRY[this.id] = this;
    }

    get template() {
        //Structure taken from UnityWebGL autogenerated page
        const id = this.id;
        return `
        <div id="${id}-unity-container" class="unity-desktop">
        <canvas id="${id}-unity-canvas" width=960 height=600></canvas>
        <div id="${id}-unity-loading-bar">
            <div id="${id}-unity-logo"></div>
            <div id="${id}-unity-progress-bar-empty">
            <div id="${id}-unity-progress-bar-full"></div>
            </div>
        </div>
        <div id="${id}-unity-warning"> </div>
        <div id="${id}-unity-footer">
            <div id="${id}-unity-webgl-logo"></div>
            <div id="${id}-unity-fullscreen-button"></div>
        </div>
        </div>
        `;
    }

    connectedCallback(){
        //Create a reference to the shadow dom root
        const root = this;
        const id = this.id;
        var container = root.querySelector(`#${id}-unity-container`);
        var canvas = root.querySelector(`#${id}-unity-canvas`);
        var loadingBar = root.querySelector(`#${id}-unity-loading-bar`);
        var progressBarFull = root.querySelector(`#${id}-unity-progress-bar-full`);
        var fullscreenButton = root.querySelector(`#${id}-unity-fullscreen-button`);
        var warningBanner = root.querySelector(`#${id}-unity-warning`);

        // Shows a temporary message banner/ribbon for a few seconds, or
        // a permanent error message on top of the canvas if type=='error'.
        // If type=='warning', a yellow highlight color is used.
        function unityShowBanner(msg, type) {
            function updateBannerVisibility() {
            warningBanner.style.display = warningBanner.children.length ? 'block' : 'none';
            }
            var div = root.createElement('div');
            div.innerHTML = msg;
            warningBanner.appendChild(div);
            if (type == 'error') div.style = 'background: red; padding: 10px;';
            else {
            if (type == 'warning') div.style = 'background: yellow; padding: 10px;';
            setTimeout(function() {
                warningBanner.removeChild(div);
                updateBannerVisibility();
            }, 5000);
            }
            updateBannerVisibility();
        }
        
        //Modify the buildUrl for different path
        var buildUrl = "build/Build";
        var loaderUrl = buildUrl + "/build.loader.js";
        var config = {
            dataUrl: buildUrl + "/build.data",
            frameworkUrl: buildUrl + "/build.framework.js",
            codeUrl: buildUrl + "/build.wasm",
            streamingAssetsUrl: "StreamingAssets",
            companyName: "DefaultCompany",
            productName: "unity-body-ui",
            productVersion: "0.1",
            showBanner: unityShowBanner,
        };

        // By default Unity keeps WebGL canvas render target size matched with
        // the DOM size of the canvas element (scaled by window.devicePixelRatio)
        if (/iPhone|iPad|iPod|Android/i.test(navigator.userAgent)) {
            // Mobile device style: fill the whole browser client area with the game canvas:

            var meta = document.createElement('meta');
            meta.name = 'viewport';
            meta.content = 'width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, shrink-to-fit=yes';
            document.getElementsByTagName('head')[0].appendChild(meta);
            container.className = "unity-mobile";

            // To lower canvas resolution on mobile devices to gain some
            // performance, uncomment the following line:
            // config.devicePixelRatio = 1;

            canvas.style.width = window.innerWidth + 'px';
            canvas.style.height = window.innerHeight + 'px';

            unityShowBanner('WebGL builds are not supported on mobile devices.');
        } else {
            // Desktop style: Render the game canvas in a window that can be maximized to fullscreen:

        }

        loadingBar.style.display = "block";

        //Start playing the unity build
        var script = document.createElement("script");
        script.src = loaderUrl;
        script.onload = () => {
            createUnityInstance(canvas, config, (progress) => {
            progressBarFull.style.width = 100 * progress + "%";
            }).then((unityInstance) => {
            loadingBar.style.display = "none";
            
            //game loaded initialize data
            this.setUnityInstance(unityInstance);

            fullscreenButton.onclick = () => {
                unityInstance.SetFullscreen(1);
            };
            }).catch((message) => {
                // alert(message);
                console.log(message);
            });
        };

        //attach to this script
        root.appendChild(script);
    }


    
    //The list of observed attributes to pass to unity
    static get observedAttributes() {
        return ['bounds', 'target', 'rotationy', 'camera',
          'rotationx', 'zoom', 'interactive', 'scene'];
    }



    setUnityInstance(unityInstance){
        //set the game instance
        this.#myGameInstance = unityInstance;
    
        //this runs async so put the id call here
        this.#myGameInstance.SendMessage("JSBridge", "SetInstance", this.id);
    
        //loop through attributes
        setTimeout(() => {
          UnityBodyUI.observedAttributes.forEach(element => {
    
            if(this.getAttribute(element)!==null){
              var newVal = Number(this.getAttribute(element));
              this.attributeChangedCallback(element, null, newVal);

              //add a listener for the outputs from unity
              this.addEventListener(element+"Change", (event) => this.setAttribute(element, event.detail));
            }
          });
        }, 1);
    }


    
    attributeChangedCallback(name, oldValue, newValue) {
        //For bounds scene and other objects, catch them in 
        if(oldValue != newValue){
            //Do some string concatination
            const functionName = `Set${name[0].toUpperCase()}${name.slice(1)}`
            
            if(this.#myGameInstance){
                //pass the data to the JSBridge
                this.#myGameInstance.SendMessage("JSBridge", functionName, newValue);
            }
        }
        else{
            console.log("Same old variable");
        }
    }
}

//define the class and use it
window.customElements.define('wc-body-ui', UnityBodyUI)